{{- if .Values.api }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-openapi
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    component: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-openapi
  template:
    metadata:
      labels:
        app: sample-openapi
        component: {{ .Release.Namespace }}
    spec:
      containers:
        - name: sample-openapi
          image: {{ .Values.images.api }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
